### PR TITLE
Fixes for Conditional Access and Intune enrollment with policies

### LINKED ISSUE #1132: Conditional access blocks Intune enrollment on first login.
### Description

Hello!

I am trying to evaluate Himmelblau for our company to use it as a replacement for authd + intune portal (We are using Ubuntu 24.04)
Things are looking promising but I there is one big problem that I am facing right now. We have CA rules that requires the devices to be compliant in order for the login to be allowed. 

The problem is if I enable the compliance setting in himmelblau (`apply_policy = true`) it gets blocked by our CA policy resulting in `AADSTSError { code: 530003 } error`. If I login with a user that is not in the CA rule it works fine. 

This is how our CA rule is configured:

```
Targeted resources: All apps

- Excluded apps: Microsoft Intune, Microsoft Intune Company Portal for Linux, Microsoft Intune Enrollment

Included users: All users (with the exception of a few test users)

Grant: Require device to be marked as compliant
```

I tried setting up the Entra ID application following this (Option A): https://himmelblau-idm.org/docs/advanced/Creating-an-Entra-ID-Application-for-Himmelblau-GroupMember.Read.All-and-User.Read.All-Permissions/

However I cannot exclude the application from the CA since it's public ( I get the `PublicClientsAreUnsupported` error).

I fail to see anything that works around this in the documentation, so the only solution that I see here is using a user that is not included in the CA for the first enrollment step, but this seems like quite a bad solution.

Thank you!

### Steps to Reproduce

1. Have CA policy that needs the device marked as compliant to allow login 
2. Try to create a first account on a machine that has Himmelblau deployed with `apply_policy = true`
3. Get the error `AADSTSError { code: 530003 } error`

### Relevant log output

```shell
8-f35dd9a4e927 ERROR       ┕━ 🚨 [error]: AADSTSError(AADSTSError { code: 530003, description: "Unknown error code" })
854-4a2aef5562c8 INFO     pam authenticate init [ 61.4ms | 0.47% / 100.00% ]
854-4a2aef5562c8 INFO     ┕━ unix_user_online_auth_init [ 61.1ms | 99.53% ] no_hello_pin: false
365-22a5311b3b93 INFO     pam account begin session [ 3.87µs | 100.00% ]
fd8-27a8420379c2 INFO     pam authenticate init [ 3.98µs | 100.00% ]
cc2-0ac634a6640c INFO     pam account begin session [ 5.03µs | 100.00% ]
78e-ee5f5ee75bbc INFO     pam account begin session [ 4.13µs | 100.00% ]
e0f-26e884d29e4c INFO     pam authenticate init [ 3.49µs | 100.00% ]
0c3-e3fb1672a789 INFO     pam account begin session [ 4.47µs | 100.00% ]
f43-512999f06c9e INFO     pam account begin session [ 3.79µs | 100.00% ]
```

### Version

2.3.5

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
---

### 💡 Help Make It Happen!

Want to see this issue resolved faster? Fund its implementation through our **Backer's Bounty** program, where you choose which issues get priority!

[Donate to Our Collective](https://himmelblau-idm.org/backers.html#backers-bounty)

For US tax exempt donations:

[Donate US Tax Exempt](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=8GYKFLX9UNCH2)

Your support helps drive Himmelblau’s evolution!

### PR DESCRIPTION
**Pull request by bluca**
Fixes #1132

Needs changes in https://gitlab.com/samba-team/libhimmelblau/-/merge_requests/139

With all of these in place, I can enroll and login with a very strict set of policies with custom scripts being sent down from the server, and Conditional Access works as expected.

### CODE REVIEW

File: src/policies/src/custom_compliance_ext.rs [hunk 1]
```diff
@@ -27,22 +27,27 @@ use std::io::Write;
...
     // Write the script contents
-    file.write_all(script.as_bytes())
+    file.write_all(normalized.as_bytes())
         .context("Failed to write script to temp file")?;
 
     // Make it executable
     let mut perms: Permissions = file.as_file().metadata()?.permissions();
-    perms.set_mode(0o700);
+    perms.set_mode(0o500);
     file.as_file().set_permissions(perms)?;
```
[the remark this answers is not in the document]
Comment (bluca) [reply src/policies/src/custom_compliance_ext.rs:58]: just a cleanup, not worth it

File: src/policies/src/custom_compliance_ext.rs [hunk 2]
```diff
@@ -55,15 +60,31 @@ fn execute_script(script: &str) -> Result<String> {
...
+    let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
+    debug!(
+        exit_code = ?output.status.code(),
+        stdout_len = stdout.len(),
+        stderr_len = stderr.len(),
+        "Custom compliance script execution finished"
+    );
+    if !stderr.is_empty() {
+        debug!(stderr = %stderr, "Custom compliance script stderr");
+    }
```
[the remark this answers is not in the document]
Comment (bluca) [reply src/policies/src/custom_compliance_ext.rs:90]: debug log is enough

File: src/policies/src/compliance_ext.rs [hunk 3]
```diff
@@ -367,7 +340,7 @@ impl ComplianceCSE {
                     }
                 }
                 unknown => {
-                    errors.push(format!("Unrecognized compliance option '{}'", unknown));
+                    warn!("Unrecognized compliance option '{}'", unknown);
```
[the remark this answers is not in the document]
Comment (bluca) [reply src/policies/src/compliance_ext.rs:344]: debug log is enough

File: src/policies/src/custom_compliance_ext.rs [hunk 4]
```diff
@@ -77,13 +98,36 @@ impl CSE for CustomComplianceCSE {
...
+                );
+                self.apply_compliance(policy).await;
+            } else {
+                debug!(
+                    policy_id = %policy.policy_id,
+                    "CustomComplianceCSE: not a custom compliance policy, skipping"
+                );
             }
         }
         Ok(true)
```
[the remark this answers is not in the document]
Comment (bluca) [reply src/policies/src/custom_compliance_ext.rs:149]: debug log is enough

File: src/policies/src/compliance_ext.rs [hunk 5]
```diff
@@ -378,4 +351,196 @@ impl ComplianceCSE {
...
+                    {
+                        // Report the actual distro as NonCompliant
+                        details[i].actual_value = system_distro.to_string();
+                        // Stays as default NonCompliant
+                    } else {
+                        // Version constraints for unsupported distro: not applicable
+                        details[i].actual_value = "".to_string();
+                        details[i].new_compliance_state = "Compliant".to_string();
+                        details[i].old_compliance_state = "Compliant".to_string();
+                    }
```
[the remark this answers is not in the document]
Comment (bluca) [reply src/policies/src/compliance_ext.rs:451]: the field must be empty

**Comment by dmulder** [comment]
Does this fix custom compliance reporting? I noticed you made some changes there.

**Comment by bluca** [comment]
> Does this fix custom compliance reporting? I noticed you made some changes there.

Yes, with this it all works for me, including first login with conditional access and custom compliance scripts being downloaded and ran

**Comment by dmulder** [comment]
@bluca looks like you've got a typo (check the CI failure):
```
 error[E0609]: no field `csp_path` on type `&PolicyDetails`
   --> src/policies/src/compliance_ext.rs:380:67
    |
380 |                 if let Some(index) = extract_distro_index(&detail.csp_path) {
    |                                                                   ^^^^^^^^ unknown field
    |
    = note: available fields are: `rule_id`, `setting_definition_item_id`, `expected_value`, `actual_value`, `error_type` ... and 3 others
```

**Comment by bluca** [comment]
> @bluca looks like you've got a typo (check the CI failure):
> 
> ```
>  error[E0609]: no field `csp_path` on type `&PolicyDetails`
>    --> src/policies/src/compliance_ext.rs:380:67
>     |
> 380 |                 if let Some(index) = extract_distro_index(&detail.csp_path) {
>     |                                                                   ^^^^^^^^ unknown field
>     |
>     = note: available fields are: `rule_id`, `setting_definition_item_id`, `expected_value`, `actual_value`, `error_type` ... and 3 others
> ```

Not a typo, as mentioned in the PR description this needs a libhimmelblau update to work: https://gitlab.com/samba-team/libhimmelblau/-/merge_requests/139

**Comment by dmulder** [comment]
> Not a typo, as mentioned in the PR description this needs a libhimmelblau update to work: https://gitlab.com/samba-team/libhimmelblau/-/merge_requests/139

AH! Right, I remember reading that now.

File: src/policies/src/custom_compliance_ext.rs [hunk 6]
```diff
@@ -27,22 +27,27 @@ use std::io::Write;
...
     let mut perms: Permissions = file.as_file().metadata()?.permissions();
-    perms.set_mode(0o700);
+    perms.set_mode(0o500);
     file.as_file().set_permissions(perms)?;
 
-    // Execute the script
-    let output = Command::new(file.path())
+    // Execute the script via sh (does not require a shebang)
+    let output = Command::new("/bin/sh")
+        .arg(file.path())
```
Comment (dmulder) [inline src/policies/src/custom_compliance_ext.rs]: This breaks scripts which aren't shell scripts (for example, I was testing with a python compliance script).

Comment (dmulder) [reply src/policies/src/custom_compliance_ext.rs]: Perhaps we could check if the script has a shebang line, and prepend the command with '/bin/sh' if the shebang line is missing?

Comment (bluca) [reply src/policies/src/custom_compliance_ext.rs]: IIRC there are even some binaries out there. How about checking if it's text, and if so if it has a shebang leave it alone, and else go through 'sh'?

Comment (dmulder) [reply src/policies/src/custom_compliance_ext.rs]: That sounds like a good approach.

Comment (bluca) [reply src/policies/src/custom_compliance_ext.rs]: Ok, applied

File: src/cli/src/main.rs [hunk 7]
```diff
@@ -831,7 +831,7 @@ async fn main() -> ExitCode {
                 debug!("Attempting SSO Broker auth ...");
                 if let Ok(broker) = BrokerClient::new().await {
                     let session_id = Uuid::new_v4().to_string();
-                    let client_id = $client_id.unwrap_or(EDGE_BROWSER_CLIENT_ID.to_string());
+                    let client_id = $client_id.unwrap_or(DEFAULT_APP_ID.to_string());
```
Comment (dmulder) [inline src/cli/src/main.rs]: This change breaks group name resolution. The default app doesn't grant us rights to read group names of our group memberships, but the Edge Browser app does.

Comment (bluca) [reply src/cli/src/main.rs]: Let me see if trying edge first and falling back to the default works

Comment (bluca) [reply src/cli/src/main.rs]: Ok I've restored the Edge app id as the first try, and if that fails, it now falls back to the default app id from libhimmelblau, which is intune's since the new version. This works for me with my setup. The only minor inconvenience is that on first enrollment there's some "stuttering" since the FIDO2 auth has to be done twice, once per app id, but it's only on the very first login so it seems fine for now, if it fixes the issue with group name resolution.
Please try again with your use case when you have a sec. Thanks!

**Review by dmulder — APPROVED** [review]
LGTM
